export const EVENTS = {
  TEST_CREATED: 'test:created',
  TEST_UPDATED: 'test:updated',
  TEST_DELETED: 'test:deleted',
  START_TEST: 'test:started',

  USER_JOINED: 'user:joined:test',
  USER_LEFT: 'user:left:test',
  USER_USED_A_CHEAT: 'user:used:a:cheat',
  USER_SUBMITTED_ANSWER: 'user:submitted:answer',
  USER_GOT_SCORE: 'user:got:score',
  USER_FINISHED_TEST: 'user:finished:test',
  USER_GOT_A_BADGE: 'user:got:a:badge',
  PROGRESS_UPDATED: 'progress:updated',
  ANSWER_SUBMITTED: 'answer:submitted',
  CREATE_TEST_BY_BOOK: 'create:test:by:book',
  CREATE_TEST_BY_FORM: 'create:test:by:form',
  ERROR: 'error',
  JOIN_TEST: 'join:test',
  LEAVE_TEST: 'leave:test',
  TEST_PROGRESS: 'test:progress',
  SUBMIT_ANSWER: 'submit:answer',
};
